import 'package:flutter/material.dart';

import 'tokens.dart';

class ThemePack {
  final String id, name, emoji;
  final GardenTokens light, dark;
  const ThemePack({
    required this.id,
    required this.name,
    required this.emoji,
    required this.light,
    required this.dark,
  });
  GardenTokens tokens(Brightness brightness) =>
      brightness == Brightness.dark ? dark : light;
}

const gardenPack = ThemePack(
  id: 'garden',
  name: 'Garden',
  emoji: '🌱',
  light: GardenTokens(),
  dark: GardenTokens(
    launchTitleShadow: Color(0xFF3F6540),
    selectedSurface: Color(0xFF30462E),
    navigation: Color(0xFF263D2B),
    navigationInk: Color(0xFFE1EBDD),
    savingSurface: Color(0xFF303E2D),
    oweSurface: Color(0xFF393045),
    launchCanvas: Color(0xFF102B24),
    headlineSide: Color(0xFF718453),
    headingShadow: Color(0xFF45553B),
    chartTrack: Color(0xFF47573B),
    loveSparkle: Color(0xFFDCF5A5),
    launchGlow: Color(0xFFDCF5A5),
    launchTrack: Colors.white12,
    canvas: Color(0xFF111C17),
    surface: Color(0xFF1D2A24),
    surfaceAlt: Color(0xFF25372E),
    ink: Color(0xFFF1F3EC),
    inkMuted: Color(0xFFBAC8BE),
    brand: Color(0xFFDCF5A5),
    onBrand: Color(0xFF173D31),
    warning: Color(0xFFFFD180),
    success: Color(0xFFABE0BE),
    danger: Color(0xFFFFB4AB),
  ),
);

GardenTokens _palette({
  required bool dark,
  required Color brand,
  required Color accent,
  required Color secondary,
  required Color canvas,
  required Color surface,
  required String font,
  required double radius,
}) {
  final ink = dark ? const Color(0xFFF8F5F6) : const Color(0xFF19191E);
  final base = dark ? gardenPack.dark : gardenPack.light;
  final hero = Color.lerp(brand, const Color(0xFF08080C), .25)!;
  return base.copyWith(
    canvas: canvas,
    surface: surface,
    surfaceAlt: Color.lerp(surface, accent, .08),
    ink: ink,
    inkMuted: dark ? const Color(0xFFC4BDC6) : const Color(0xFF57515B),
    brand: dark ? accent : brand,
    onBrand: dark ? const Color(0xFF19191E) : const Color(0xFFFFFFFF),
    receive: accent,
    onReceive: const Color(0xFF19191E),
    owe: secondary,
    onOwe: const Color(0xFF19191E),
    hero: hero,
    heroGradient: [hero, Color.lerp(hero, const Color(0xFF000000), .5)!],
    heroInk: const Color(0xFFFFFFFF),
    heroMuted: const Color(0xFFEAE5ED),
    selectedSurface: dark ? Color.lerp(surface, accent, .22) : accent,
    oweSurface: dark ? Color.lerp(surface, secondary, .22) : secondary,
    navigation: Color.lerp(surface, accent, .20),
    navigationInk: ink,
    savingSurface: Color.lerp(surface, accent, .16),
    splitAccent: secondary,
    goalAccent: accent,
    entryAccent: Color.lerp(accent, secondary, .45),
    expenseAccent: secondary,
    heroShadow: Color.lerp(hero, const Color(0xFF000000), .35),
    heroDivider: Color.lerp(hero, accent, .35),
    warning: dark ? const Color(0xFFFFD180) : const Color(0xFF805500),
    success: dark ? const Color(0xFFABE0BE) : const Color(0xFF24633C),
    danger: dark ? const Color(0xFFFFB4AB) : const Color(0xFFAB302B),
    leafHighlight: accent,
    leafMidtone: Color.lerp(accent, brand, .35),
    leafShade: brand,
    leafShadow: hero,
    plantShadow: brand,
    sparkle: brand,
    loveSparkle: accent,
    plantCheek: secondary,
    launchCanvas: hero,
    launchGlow: accent,
    launchPetal: secondary,
    launchLeafHighlight: accent,
    launchLeafMidtone: brand,
    launchLeafTip: accent,
    launchLeafShade: brand,
    launchLeafEdge: secondary,
    launchStem: accent,
    launchTitleShadow: brand,
    particlePetal: secondary,
    particleLeaf: accent,
    headingShadow: Color.lerp(canvas, brand, .15),
    headlineSide: Color.lerp(canvas, brand, .3),
    chartTrack: Color.lerp(surface, accent, .3),
    chart: [
      accent,
      secondary,
      const Color(0xFFFFCD91),
      const Color(0xFFA5D9F1),
      const Color(0xFFD2C4FA),
      const Color(0xFFC5E9A3),
    ],
    displayFont: font,
    radius: radius,
  );
}

ThemePack _pack(
  String id,
  String name,
  String emoji,
  String font,
  double radius,
  int brand,
  int accent,
  int secondary,
  int canvas,
  int darkCanvas,
  int darkSurface,
) => ThemePack(
  id: id,
  name: name,
  emoji: emoji,
  light: _palette(
    dark: false,
    brand: Color(brand),
    accent: Color(accent),
    secondary: Color(secondary),
    canvas: Color(canvas),
    surface: const Color(0xFFFFFFFF),
    font: font,
    radius: radius,
  ),
  dark: _palette(
    dark: true,
    brand: Color(brand),
    accent: Color(accent),
    secondary: Color(secondary),
    canvas: Color(darkCanvas),
    surface: Color(darkSurface),
    font: font,
    radius: radius,
  ),
);
final themePacks = [
  gardenPack,
  _pack(
    'sakura',
    'Sakura Bloom',
    '🌸',
    'Fredoka',
    32,
    0xFFC2185B,
    0xFFFFD6E4,
    0xFFCDEFE3,
    0xFFFFF7F9,
    0xFF1E1418,
    0xFF2A1D23,
  ),
  _pack(
    'neon',
    'Midnight Neon',
    '⚡',
    'SpaceGrotesk',
    16,
    0xFF0E0E1A,
    0xFFC6FF3D,
    0xFFFF83CA,
    0xFFF7F7FC,
    0xFF0A0A14,
    0xFF15152A,
  ),
  _pack(
    'mango',
    'Mango Sunset',
    '🥭',
    'DMSerifDisplay',
    24,
    0xFFA34823,
    0xFFFFC56B,
    0xFFFFE3D3,
    0xFFFFF8F1,
    0xFF1C1410,
    0xFF2A1E18,
  ),
  _pack(
    'ocean',
    'Ocean Mist',
    '🌊',
    'Quicksand',
    30,
    0xFF0F5E6B,
    0xFFBDEFF0,
    0xFFD6F2E6,
    0xFFF2F8F9,
    0xFF0C1A1F,
    0xFF15272E,
  ),
];
ThemePack themePack(String id) =>
    themePacks.where((p) => p.id == id).firstOrNull ?? gardenPack;
